whole_body_controller:
    chain_array:
        - tip_name: grippoint_left
            - grippoint_left
            - shoulder_mount_left
            - base
      
        - tip_name: grippoint_right
            - grippoint_right
            - shoulder_mount_right
            - base 