#!/usr/bin/env python

'''
Send a Cartesian Motion Objective

Usage:
  cartesionmotionobjective left  <x> <y> <z> [<roll> <pitch> <yaw>] [--frame=FRAME]
  cartesionmotionobjective right <x> <y> <z> [<roll> <pitch> <yaw>] [--frame=FRAME]
  cartesionmotionobjective cancel
  cartesionmotionobjective -h | --help

Options:
  -h --help      Show this screen.
  --frame=FRAME  Which frame the coordinate is specified in [default: base_link]
'''

from docopt import docopt
import roslib; roslib.load_manifest('amigo_whole_body_controller')
import rospy
import actionlib

from amigo_whole_body_controller.msg import *
from arm_navigation_msgs.msg import *
from tf.transformations import quaternion_from_euler

def euler_z_to_orientation_goal(orientation=None):
    roll  = orientation[0] if orientation else 0
    pitch = orientation[0] if orientation else 0
    yaw   = orientation[0] if orientation else 0

    q = geometry_msgs.msg.Quaternion(*quaternion_from_euler(roll, pitch, yaw))

    # header,link_name,type,orientation,
    # absolute_roll_tolerance,absolute_pitch_tolerance,absolute_yaw_tolerance
    # weight

    return OrientationConstraint(
        orientation=q)

class CartesianMotionObjective():

    stiffnessfactor = 4.0

    def __init__(self):
        self.force = (
            70.0 * self.stiffnessfactor,
            70.0 * self.stiffnessfactor,
            50.0 * self.stiffnessfactor)
        self.torque = (
            5.0 * self.stiffnessfactor,
            5.0 * self.stiffnessfactor,
            5.0 * self.stiffnessfactor)

        self.action_client = actionlib.SimpleActionClient("add_motion_objective", ArmTaskAction)
        self.action_client.feedback_cb = self.feedback_cb

        self.action_client.wait_for_server()
        rospy.loginfo("Connected to action server")

    def build_goal(self, link_name, position, orientation, frame_id):
        self.position    = position
        orientation_goal = euler_z_to_orientation_goal(orientation)

        force = self.force
        torque = self.torque if orientation else (0, 0, 0)

        position_constraint = PositionConstraint(
            header=std_msgs.msg.Header(frame_id=frame_id),
            link_name=link_name,
            position=geometry_msgs.msg.Point(*self.position))

        stiffness = geometry_msgs.msg.Wrench(
            force=geometry_msgs.msg.Vector3(*force),
            torque=geometry_msgs.msg.Vector3(*torque))

        goal = ArmTaskGoal(
            goal_type='grasp',
            position_constraint=position_constraint,
            orientation_constraint=orientation_goal,
            stiffness=stiffness)
        return goal

    def send_goal(self, goal):
        rospy.loginfo("Sending goal...")
        print goal

        rospy.loginfo("Waiting for result...")
        self.action_client.send_goal(goal,
            done_cb=None, active_cb=None, feedback_cb=self.feedback_cb)

    def wait_for_result(self):
        finished = False
        try:
            finished = self.action_client.wait_for_result()
        except KeyboardInterrupt:
            print "Canceling goal..."
            self.action_client.cancel_goal()
            self.action_client.wait_for_result(rospy.Duration(0.5))
        if not finished:
            return

        rospy.loginfo("Result!")
        result = self.action_client.get_result()
        print result

    last_feedback = None
    def feedback_cb(self, feedback):
        code = feedback.status_code.status
        if code != self.last_feedback:
            print 'feedback!!!', code
            self.last_feedback = code

if __name__ == '__main__':
    arguments = docopt(__doc__)
    print arguments

    try:
        # disable signals so we can detect a KeyboardInterrupt
        rospy.init_node('cartesionmotionobjective', anonymous=True, disable_signals=True)

        if arguments['cancel']:
            cmo = CartesianMotionObjective()
            cmo.action_client.cancel_all_goals()
            cmo.action_client.wait_for_server()

        elif arguments['left'] or arguments['right']:

            for side in ['left', 'right']:
                if arguments[side]:
                    link_name = "grippoint_" + side
                    break

            position = (
                float(arguments['<x>']) ,
                float(arguments['<y>']) ,
                float(arguments['<z>']) )
            if arguments['<roll>']:
                orientation = (
                    float(arguments['<roll>' ]) ,
                    float(arguments['<pitch>']) ,
                    float(arguments['<yaw>'  ]) )
            else:
                orientation = None
            frame_id = arguments['--frame']

            print 'creating motion objective...'
            cmo = CartesianMotionObjective()
            print 'sending goal...'
            cmo.send_goal(cmo.build_goal(link_name=link_name,
                                         position=position,
                                         orientation=orientation,
                                         frame_id=frame_id))
            print 'waiting for result...'
            cmo.wait_for_result()

    except KeyboardInterrupt:
        print "program interrupted before completion"
